### ISSUE TITLE
hot to run .py file

### ISSUE THREAD

**Issue by kucingkembar** [luanon404/Selenium-On-Termux-Android#6]
sorry for the newbie question, 
how to run a .py file?

**Comment by luanon404** [comment]
python a.py

**Comment by kucingkembar** [comment]
owh my god so fast,
i will try
thank you so much

**Comment by kucingkembar** [comment]
after some time i get this linux thing, 
in the pkg installation, you must try multiple times to work,
and some pkg is not installable,
thank you, now the screenshot.png in my download folder
